# use the official centos 7 base image
FROM centos:centos7
# Install the apache HTTP serve package from the ncentos repository
RUN yum install httpd -y
#copy the index.html filr from the Docker build context to the default Apache document root directory in the container
COPY index.html/var/www/html/
# specify the command to run when the container starts,which starts the Apache HTTP server in the foreground
CMD ["/usr/sbin/httpd","-D","FOREGROUND"]
# Expose port 80 to allow incoming HTTP traffuic to the container
EXPOSE 80          